name: e_commerce
description: "A Flutter new concept application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  provider:
  cupertino_icons:
  flutter_iconly:
  shimmer:
  fancy_shimmer_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/userAssets/images/
    - assets/
    - assets/userAssets/images/bag/
    - assets/userAssets/images/profile/
    - assets/userAssets/images/categories/
    - assets/userAssets/images/banners/
    - assets/userAssets/
